# Generated by Django 6.0.3 on 2026-03-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='analyzed_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
