# Generated by Django 6.0.3 on 2026-03-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_jobdescription_analyzed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='format_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='score_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
